### ISSUE TITLE
Add HTTPS support for Youku

### ISSUE THREAD

**Issue by jichizhang** [s9e/flarum-ext-mediaembed#5]
All Youku videos went blank on HTTPS forums, because "player.youku.com" does not have SSL support. But actually Youku does support HTTPS, with a different URL.

e.g.
Original link: http://v.youku.com/v_show/id_XMTU0MzMyNjg2NA.html
HTTP player: http://player.youku.com/embed/XMTU0MzMyNjg2NA
HTTPS player: https://players.youku.com/player.php/sid/XMTU0MzMyNjg2NA/v.swf

I think it's better to use the HTTPS player at any time.

**Comment by JoshyPHP** [comment]
Thanks for the heads-up. However, I tried their HTTPS player but it doesn't work for me because of mixed content. The culprit is this line in their page source code, which loads over HTTP (not HTTPS) and on the wrong domain ("player" and not "players"):

```
script.src = 'http://player.youku.com/jsapi';
```

To work with the HTTPS player it should be:

```
script.src = '/jsapi';
```

If you don't mind notifying Youku's developers so that they can fix it, I'll update the iframe as soon as it's done.

**Comment by jichizhang** [comment]
Both directory and domain are different. If you only change the domain, it won't work because of mixed content.

HTTP player: 
http://player.youku.com/embed/$video-id

HTTPS player:
https://players.youku.com/player.php/sid/$video-id/v.swf

**Comment by jichizhang** [comment]
I tried to edit by myself, but I got this error after I edit `src/Plugins/MediaEmbed/Configurator/CachedSiteDefinitionProvider.php` and `src/Bundles/MediaPack/Renderer.php`

`Notice: unserialize(): Error at offset 201 of 207 bytes in /path/to/flarum/vendor/s9e/text-formatter/src/Plugins/MediaEmbed/Configurator/CachedSiteDefinitionProvider.php on line 124`

`Fatal error: Uncaught TypeError: Argument 2 passed to s9e\TextFormatter\Plugins\MediaEmbed\Configurator\TemplateBuilder::build() must be of the type array, boolean given, called in /path/to/flarum/vendor/s9e/text-formatter/src/Plugins/MediaEmbed/Configurator.php on line 122 and defined in /path/to/flarum/vendor/s9e/text-formatter/src/Plugins/MediaEmbed/Configurator/TemplateBuilder.php:23 Stack trace: #0 /path/to/flarum/vendor/s9e/text-formatter/src/Plugins/MediaEmbed/Configurator.php(122): s9e\TextFormatter\Plugins\MediaEmbed\Configurator\TemplateBuilder->build('youku', false) #1 /path/to/flarum/vendor/s9e/text-formatter/src/Configurator/Bundles/MediaPack.php(22): s9e\TextFormatter\Plugins\MediaEmbed\Configurator->add('youku') #2 /path/to/flarum/extensions/s9e-mediaembed/bootstrap.php(20): s9e\TextFormatter\Configurator\Bundles\MediaPack->configure(Object(s9e\TextFormatter\Configurator)) #3 [internal function]: s9e\Flarum\MediaEmbed\{closure}(Object(Flarum\Event\ConfigureFormatter)) #4 /path/to/flarum/vendor/illuminate/events/D in /path/to/flarum/vendor/s9e/text-formatter/src/Plugins/MediaEmbed/Configurator/TemplateBuilder.php on line 23`

**Comment by JoshyPHP** [comment]
> Both directory and domain are different. If you only change the domain, it won't work because of mixed content.

Right, we were talking about different things. I was talking about accessing their embed page via their secure domain and you're proposing replacing the `iframe` with a Flash object. I'll look into it.

You won't be able to edit the data in `CachedSiteDefinitionProvider` by hand because it's serialized.

**Comment by AdamSEMbyotic** [comment]
Hey Guys, I'm not sure if it's still relevant or not but I stumbled across this thread while trying to convert one of our sites to HTTPS that uses Youku. I found the HTTPS URL for the jsapi by looking a little more closely into the code of the non-https jsapi. The HTTPS URL is: https://players.youku.com/jsapi. Unfortunately you can't uses a protocol-less URL since the URLs aren't the same.

Hopefully this helps someone else.
